name: flutter_ringtone_player
description: A simple player for system default ringtones, alarms and notifications
version: 2.0.0
homepage: https://github.com/inway/flutter_ringtone_player
repository: https://github.com/inway/flutter_ringtone_player

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.inway.ringtone.player
        pluginClass: FlutterRingtonePlayerPlugin
      ios:
        pluginClass: FlutterRingtonePlayerPlugin
